### ISSUE TITLE
Getting issue in Age Detection Notebook 

### ISSUE THREAD

**Issue by maria-zafar** [shubham0204/Google_Colab_Notebooks#2]
![image](https://user-images.githubusercontent.com/69984290/137509841-48ade318-3996-4103-81d3-fae4973c9d37.png)
hello can you help in resolving this issue?

**Comment by shubham0204** [comment]
@maria-zafar  Are you using the default UTKFace dataset or some other dataset?

**Comment by maria-zafar** [comment]
@shubham0204 default UTK

**Comment by shubham0204** [comment]
@maria-zafar  Have you made any modifications in the notebook? If possible, could you share a copy of your notebook?

**Comment by maria-zafar** [comment]
![image](https://user-images.githubusercontent.com/69984290/137590993-c20364d0-6958-4cd8-8275-43579ed4df3a.png)
![image](https://user-images.githubusercontent.com/69984290/137591007-6e90e99b-6178-4e96-9ca1-0a9757019e5b.png)

No i have not done any major changes other than changing the dir path

**Comment by maria-zafar** [comment]
![image](https://user-images.githubusercontent.com/69984290/137591086-2e795210-d2ad-4630-9834-54d45f3b611b.png)

![image](https://user-images.githubusercontent.com/69984290/137591076-3f2c9743-1adb-459c-a6ca-d794ca76d627.png)
 @shubham0204 I have not made any major changes other than changing file paths

**Comment by shubham0204** [comment]
You need to use the `UTKFace.tar.gz` file and not `crop_part1.tar.gz`. See [this](https://drive.google.com/file/d/0BxYys69jI14kYVM3aVhKS1VhRUk/view?usp=sharing&resourcekey=0-dabpv_3J0C0cditpiAfhAw) file. I ran the notebook once again, and it works correctly in Google Colab.
